program: main.py
method: random
metric:
  goal: maximize
  name: validation accuracy
parameters:

  run: 
    value: sweep
  
  NUM_NODE_FEATS:
    value: 54
  MOL_FEATURIZER:
    value: 'mol_to_graph_full'
  REWARD_MODULES:
    value: ['SIZE','SYNTH']
    
  # ACTOR_VARIABLES: 
  HIDDEN_DIM_A:
    values: [450,500,600,650]

  NUM_ATOM_TYPES_A:
    value:  17
  DROPOUT_A: 
    distribution: uniform
    min: .6
    max: .85
  GRAPH_ACTIVATION_A: 
    value: 'ReLU'
  DENSE_ACTIVATION_A: 
    values: ['ReLU','ELU','LeakyReLU']
  MODEL_TYPE_A:  
    value: GatedGraphConv
  GRAPH_NUM_LAYERS_A: 
    values: [3,4,5]
  DENSE_NUM_LAYERS_A: 
    values: [3,4,5]
  DENSE_NORMALIZATION_A:
    values: ['LayerNorm','SpectralNorm', 'None']


  # CRITIC_VARIABLES:
  HIDDEN_DIM_C: 
    values: [450,500,600,650]
  MODEL_TYPE_C:  
    value: GatedGraphConv
  GRAPH_NUM_LAYERS_C: 
    values: [3,4,5]
  DENSE_NUM_LAYERS_C: 
    values: [3,4,5]
  GRAPH_ACTIVATION_C: 
    value: 'ReLU'
  DENSE_ACTIVATION_C: 
    values: ['ReLU','ELU','LeakyReLU']
  DROPOUT_C:  
    values: [0]
  DENSE_NORMALIZATION_C:
    values: ['LayerNorm','SpectralNorm', 'None']




  # PPO_VARIABLES :
  PPO_BATCH_SIZE : 
    values: [32,64,128,256,512]
  TIMESTEPS_PER_ITERATION : 
    values: [2500,3500,4500]
  CLIP: 
    distribution: uniform
    min: .05
    max: .3
  A_LR: 
    distribution: normal
    mu: 3e-4
    sigma: 3e-5
  C_LR : 
    distribution: normal
    mu: 3e-4
    sigma: 3e-5
  NUM_UPDATED_PER_ITERATION: 
    values: [3,4,5,6,7]
  MAX_TIMESTEPS_PER_EPISODE: 
    value: 40
  GAMMA: 
    distribution: uniform
    min: .95
    max: .99




  # SUPERVISED_TRAINING_VARIABLES:
  SUPERVSED_LR : 
    distribution: normal
    mu: 3e-4
    sigma: 3e-5
  SUPERVISED_LR_DECAY : 
      distribution: uniform
      min: .88
      max: .95
  SUPERVISED_BATCH_SIZE: 
      values: [128,256,512,1024]
  DATASET_SIZE: 
      value: 507528
  PATH: 
      value: '../GraphDecomp/graph_decomp/graphs'

  # FINAL_TRAINING_VARIABLES:
  SV_EPOCHS: 
      values: [8,12,16]
  PPO_STEPS: 
      value: 0

  
